// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortEval.Infrastructure;

namespace PortEval.Infrastructure.Migrations
{
    [DbContext(typeof(PortEvalDbContext))]
    [Migration("20220330101403_ImportsTableAdded")]
    partial class ImportsTableAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Chart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Charts");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.ChartLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChartId")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Dash")
                        .HasColumnType("int");

                    b.Property<string>("Line_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChartId");

                    b.ToTable("ChartLines");

                    b.HasDiscriminator<string>("Line_Type").HasValue("ChartLine");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Code = "AED",
                            IsDefault = false,
                            Name = "UAE dirham",
                            Symbol = "د.إ;",
                            Version = 0
                        },
                        new
                        {
                            Code = "AFN",
                            IsDefault = false,
                            Name = "Afghan afghani",
                            Symbol = "Afs",
                            Version = 0
                        },
                        new
                        {
                            Code = "ALL",
                            IsDefault = false,
                            Name = "Albanian lek",
                            Symbol = "L",
                            Version = 0
                        },
                        new
                        {
                            Code = "AMD",
                            IsDefault = false,
                            Name = "Armenian dram",
                            Symbol = "AMD",
                            Version = 0
                        },
                        new
                        {
                            Code = "ANG",
                            IsDefault = false,
                            Name = "Netherlands Antillean gulden",
                            Symbol = "NAƒ",
                            Version = 0
                        },
                        new
                        {
                            Code = "AOA",
                            IsDefault = false,
                            Name = "Angolan kwanza",
                            Symbol = "Kz",
                            Version = 0
                        },
                        new
                        {
                            Code = "ARS",
                            IsDefault = false,
                            Name = "Argentine peso",
                            Symbol = "$",
                            Version = 0
                        },
                        new
                        {
                            Code = "AUD",
                            IsDefault = false,
                            Name = "Australian dollar",
                            Symbol = "$",
                            Version = 0
                        },
                        new
                        {
                            Code = "AWG",
                            IsDefault = false,
                            Name = "Aruban florin",
                            Symbol = "ƒ",
                            Version = 0
                        },
                        new
                        {
                            Code = "AZN",
                            IsDefault = false,
                            Name = "Azerbaijani manat",
                            Symbol = "AZN",
                            Version = 0
                        },
                        new
                        {
                            Code = "BAM",
                            IsDefault = false,
                            Name = "Bosnia and Herzegovina konvertibilna marka",
                            Symbol = "KM",
                            Version = 0
                        },
                        new
                        {
                            Code = "BBD",
                            IsDefault = false,
                            Name = "Barbadian dollar",
                            Symbol = "Bds$",
                            Version = 0
                        },
                        new
                        {
                            Code = "BDT",
                            IsDefault = false,
                            Name = "Bangladeshi taka",
                            Symbol = "৳",
                            Version = 0
                        },
                        new
                        {
                            Code = "BGN",
                            IsDefault = false,
                            Name = "Bulgarian lev",
                            Symbol = "BGN",
                            Version = 0
                        },
                        new
                        {
                            Code = "BHD",
                            IsDefault = false,
                            Name = "Bahraini dinar",
                            Symbol = ".د.ب",
                            Version = 0
                        },
                        new
                        {
                            Code = "BIF",
                            IsDefault = false,
                            Name = "Burundi franc",
                            Symbol = "FBu",
                            Version = 0
                        },
                        new
                        {
                            Code = "BMD",
                            IsDefault = false,
                            Name = "Bermudian dollar",
                            Symbol = "BD$",
                            Version = 0
                        },
                        new
                        {
                            Code = "BND",
                            IsDefault = false,
                            Name = "Brunei dollar",
                            Symbol = "B$",
                            Version = 0
                        },
                        new
                        {
                            Code = "BOB",
                            IsDefault = false,
                            Name = "Bolivian boliviano",
                            Symbol = "Bs.",
                            Version = 0
                        },
                        new
                        {
                            Code = "BRL",
                            IsDefault = false,
                            Name = "Brazilian real",
                            Symbol = "R$",
                            Version = 0
                        },
                        new
                        {
                            Code = "BSD",
                            IsDefault = false,
                            Name = "Bahamian dollar",
                            Symbol = "B$",
                            Version = 0
                        },
                        new
                        {
                            Code = "BTN",
                            IsDefault = false,
                            Name = "Bhutanese ngultrum",
                            Symbol = "Nu.",
                            Version = 0
                        },
                        new
                        {
                            Code = "BWP",
                            IsDefault = false,
                            Name = "Botswana pula",
                            Symbol = "P",
                            Version = 0
                        },
                        new
                        {
                            Code = "BYR",
                            IsDefault = false,
                            Name = "Belarusian ruble",
                            Symbol = "Br",
                            Version = 0
                        },
                        new
                        {
                            Code = "BZD",
                            IsDefault = false,
                            Name = "Belize dollar",
                            Symbol = "BZ$",
                            Version = 0
                        },
                        new
                        {
                            Code = "CAD",
                            IsDefault = false,
                            Name = "Canadian dollar",
                            Symbol = "$",
                            Version = 0
                        },
                        new
                        {
                            Code = "CDF",
                            IsDefault = false,
                            Name = "Congolese franc",
                            Symbol = "F",
                            Version = 0
                        },
                        new
                        {
                            Code = "CHF",
                            IsDefault = false,
                            Name = "Swiss franc",
                            Symbol = "Fr.",
                            Version = 0
                        },
                        new
                        {
                            Code = "CLP",
                            IsDefault = false,
                            Name = "Chilean peso",
                            Symbol = "$",
                            Version = 0
                        },
                        new
                        {
                            Code = "CNY",
                            IsDefault = false,
                            Name = "Chinese/Yuan renminbi",
                            Symbol = "¥",
                            Version = 0
                        },
                        new
                        {
                            Code = "COP",
                            IsDefault = false,
                            Name = "Colombian peso",
                            Symbol = "Col$",
                            Version = 0
                        },
                        new
                        {
                            Code = "CRC",
                            IsDefault = false,
                            Name = "Costa Rican colon",
                            Symbol = "₡",
                            Version = 0
                        },
                        new
                        {
                            Code = "CUC",
                            IsDefault = false,
                            Name = "Cuban peso",
                            Symbol = "$",
                            Version = 0
                        },
                        new
                        {
                            Code = "CVE",
                            IsDefault = false,
                            Name = "Cape Verdean escudo",
                            Symbol = "Esc",
                            Version = 0
                        },
                        new
                        {
                            Code = "CZK",
                            IsDefault = false,
                            Name = "Czech koruna",
                            Symbol = "Kč",
                            Version = 0
                        },
                        new
                        {
                            Code = "DJF",
                            IsDefault = false,
                            Name = "Djiboutian franc",
                            Symbol = "Fdj",
                            Version = 0
                        },
                        new
                        {
                            Code = "DKK",
                            IsDefault = false,
                            Name = "Danish krone",
                            Symbol = "Kr",
                            Version = 0
                        },
                        new
                        {
                            Code = "DOP",
                            IsDefault = false,
                            Name = "Dominican peso",
                            Symbol = "RD$",
                            Version = 0
                        },
                        new
                        {
                            Code = "DZD",
                            IsDefault = false,
                            Name = "Algerian dinar",
                            Symbol = "د.ج",
                            Version = 0
                        },
                        new
                        {
                            Code = "EEK",
                            IsDefault = false,
                            Name = "Estonian kroon",
                            Symbol = "KR",
                            Version = 0
                        },
                        new
                        {
                            Code = "EGP",
                            IsDefault = false,
                            Name = "Egyptian pound",
                            Symbol = "£",
                            Version = 0
                        },
                        new
                        {
                            Code = "ERN",
                            IsDefault = false,
                            Name = "Eritrean nakfa",
                            Symbol = "Nfa",
                            Version = 0
                        },
                        new
                        {
                            Code = "ETB",
                            IsDefault = false,
                            Name = "Ethiopian birr",
                            Symbol = "Br",
                            Version = 0
                        },
                        new
                        {
                            Code = "EUR",
                            IsDefault = false,
                            Name = "European Euro",
                            Symbol = "€",
                            Version = 0
                        },
                        new
                        {
                            Code = "FJD",
                            IsDefault = false,
                            Name = "Fijian dollar",
                            Symbol = "FJ$",
                            Version = 0
                        },
                        new
                        {
                            Code = "FKP",
                            IsDefault = false,
                            Name = "Falkland Islands pound",
                            Symbol = "£",
                            Version = 0
                        },
                        new
                        {
                            Code = "GBP",
                            IsDefault = false,
                            Name = "British pound",
                            Symbol = "£",
                            Version = 0
                        },
                        new
                        {
                            Code = "GEL",
                            IsDefault = false,
                            Name = "Georgian lari",
                            Symbol = "GEL",
                            Version = 0
                        },
                        new
                        {
                            Code = "GHS",
                            IsDefault = false,
                            Name = "Ghanaian cedi",
                            Symbol = "GH₵",
                            Version = 0
                        },
                        new
                        {
                            Code = "GIP",
                            IsDefault = false,
                            Name = "Gibraltar pound",
                            Symbol = "£",
                            Version = 0
                        },
                        new
                        {
                            Code = "GMD",
                            IsDefault = false,
                            Name = "Gambian dalasi",
                            Symbol = "D",
                            Version = 0
                        },
                        new
                        {
                            Code = "GNF",
                            IsDefault = false,
                            Name = "Guinean franc",
                            Symbol = "FG",
                            Version = 0
                        },
                        new
                        {
                            Code = "GQE",
                            IsDefault = false,
                            Name = "Central African CFA franc",
                            Symbol = "CFA",
                            Version = 0
                        },
                        new
                        {
                            Code = "GTQ",
                            IsDefault = false,
                            Name = "Guatemalan quetzal",
                            Symbol = "Q",
                            Version = 0
                        },
                        new
                        {
                            Code = "GYD",
                            IsDefault = false,
                            Name = "Guyanese dollar",
                            Symbol = "GY$",
                            Version = 0
                        },
                        new
                        {
                            Code = "HKD",
                            IsDefault = false,
                            Name = "Hong Kong dollar",
                            Symbol = "HK$",
                            Version = 0
                        },
                        new
                        {
                            Code = "HNL",
                            IsDefault = false,
                            Name = "Honduran lempira",
                            Symbol = "L",
                            Version = 0
                        },
                        new
                        {
                            Code = "HRK",
                            IsDefault = false,
                            Name = "Croatian kuna",
                            Symbol = "kn",
                            Version = 0
                        },
                        new
                        {
                            Code = "HTG",
                            IsDefault = false,
                            Name = "Haitian gourde",
                            Symbol = "G",
                            Version = 0
                        },
                        new
                        {
                            Code = "HUF",
                            IsDefault = false,
                            Name = "Hungarian forint",
                            Symbol = "Ft",
                            Version = 0
                        },
                        new
                        {
                            Code = "IDR",
                            IsDefault = false,
                            Name = "Indonesian rupiah",
                            Symbol = "Rp",
                            Version = 0
                        },
                        new
                        {
                            Code = "ILS",
                            IsDefault = false,
                            Name = "Israeli new sheqel",
                            Symbol = "₪",
                            Version = 0
                        },
                        new
                        {
                            Code = "INR",
                            IsDefault = false,
                            Name = "Indian rupee",
                            Symbol = "₹",
                            Version = 0
                        },
                        new
                        {
                            Code = "IQD",
                            IsDefault = false,
                            Name = "Iraqi dinar",
                            Symbol = "د.ع",
                            Version = 0
                        },
                        new
                        {
                            Code = "IRR",
                            IsDefault = false,
                            Name = "Iranian rial",
                            Symbol = "IRR",
                            Version = 0
                        },
                        new
                        {
                            Code = "ISK",
                            IsDefault = false,
                            Name = "Icelandic króna",
                            Symbol = "kr",
                            Version = 0
                        },
                        new
                        {
                            Code = "JMD",
                            IsDefault = false,
                            Name = "Jamaican dollar",
                            Symbol = "J$",
                            Version = 0
                        },
                        new
                        {
                            Code = "JOD",
                            IsDefault = false,
                            Name = "Jordanian dinar",
                            Symbol = "JOD",
                            Version = 0
                        },
                        new
                        {
                            Code = "JPY",
                            IsDefault = false,
                            Name = "Japanese yen",
                            Symbol = "¥",
                            Version = 0
                        },
                        new
                        {
                            Code = "KES",
                            IsDefault = false,
                            Name = "Kenyan shilling",
                            Symbol = "KSh",
                            Version = 0
                        },
                        new
                        {
                            Code = "KGS",
                            IsDefault = false,
                            Name = "Kyrgyzstani som",
                            Symbol = "сом",
                            Version = 0
                        },
                        new
                        {
                            Code = "KHR",
                            IsDefault = false,
                            Name = "Cambodian riel",
                            Symbol = "៛",
                            Version = 0
                        },
                        new
                        {
                            Code = "KMF",
                            IsDefault = false,
                            Name = "Comorian franc",
                            Symbol = "KMF",
                            Version = 0
                        },
                        new
                        {
                            Code = "KPW",
                            IsDefault = false,
                            Name = "North Korean won",
                            Symbol = "W",
                            Version = 0
                        },
                        new
                        {
                            Code = "KRW",
                            IsDefault = false,
                            Name = "South Korean won",
                            Symbol = "W",
                            Version = 0
                        },
                        new
                        {
                            Code = "KWD",
                            IsDefault = false,
                            Name = "Kuwaiti dinar",
                            Symbol = "KWD",
                            Version = 0
                        },
                        new
                        {
                            Code = "KYD",
                            IsDefault = false,
                            Name = "Cayman Islands dollar",
                            Symbol = "KY$",
                            Version = 0
                        },
                        new
                        {
                            Code = "KZT",
                            IsDefault = false,
                            Name = "Kazakhstani tenge",
                            Symbol = "T",
                            Version = 0
                        },
                        new
                        {
                            Code = "LAK",
                            IsDefault = false,
                            Name = "Lao kip",
                            Symbol = "KN",
                            Version = 0
                        },
                        new
                        {
                            Code = "LBP",
                            IsDefault = false,
                            Name = "Lebanese lira",
                            Symbol = "£",
                            Version = 0
                        },
                        new
                        {
                            Code = "LKR",
                            IsDefault = false,
                            Name = "Sri Lankan rupee",
                            Symbol = "Rs",
                            Version = 0
                        },
                        new
                        {
                            Code = "LRD",
                            IsDefault = false,
                            Name = "Liberian dollar",
                            Symbol = "L$",
                            Version = 0
                        },
                        new
                        {
                            Code = "LSL",
                            IsDefault = false,
                            Name = "Lesotho loti",
                            Symbol = "M",
                            Version = 0
                        },
                        new
                        {
                            Code = "LTL",
                            IsDefault = false,
                            Name = "Lithuanian litas",
                            Symbol = "Lt",
                            Version = 0
                        },
                        new
                        {
                            Code = "LVL",
                            IsDefault = false,
                            Name = "Latvian lats",
                            Symbol = "Ls",
                            Version = 0
                        },
                        new
                        {
                            Code = "LYD",
                            IsDefault = false,
                            Name = "Libyan dinar",
                            Symbol = "LD",
                            Version = 0
                        },
                        new
                        {
                            Code = "MAD",
                            IsDefault = false,
                            Name = "Moroccan dirham",
                            Symbol = "MAD",
                            Version = 0
                        },
                        new
                        {
                            Code = "MDL",
                            IsDefault = false,
                            Name = "Moldovan leu",
                            Symbol = "MDL",
                            Version = 0
                        },
                        new
                        {
                            Code = "MGA",
                            IsDefault = false,
                            Name = "Malagasy ariary",
                            Symbol = "FMG",
                            Version = 0
                        },
                        new
                        {
                            Code = "MKD",
                            IsDefault = false,
                            Name = "Macedonian denar",
                            Symbol = "MKD",
                            Version = 0
                        },
                        new
                        {
                            Code = "MMK",
                            IsDefault = false,
                            Name = "Myanma kyat",
                            Symbol = "K",
                            Version = 0
                        },
                        new
                        {
                            Code = "MNT",
                            IsDefault = false,
                            Name = "Mongolian tugrik",
                            Symbol = "₮",
                            Version = 0
                        },
                        new
                        {
                            Code = "MOP",
                            IsDefault = false,
                            Name = "Macanese pataca",
                            Symbol = "P",
                            Version = 0
                        },
                        new
                        {
                            Code = "MRO",
                            IsDefault = false,
                            Name = "Mauritanian ouguiya",
                            Symbol = "UM",
                            Version = 0
                        },
                        new
                        {
                            Code = "MUR",
                            IsDefault = false,
                            Name = "Mauritian rupee",
                            Symbol = "Rs",
                            Version = 0
                        },
                        new
                        {
                            Code = "MVR",
                            IsDefault = false,
                            Name = "Maldivian rufiyaa",
                            Symbol = "Rf",
                            Version = 0
                        },
                        new
                        {
                            Code = "MWK",
                            IsDefault = false,
                            Name = "Malawian kwacha",
                            Symbol = "MK",
                            Version = 0
                        },
                        new
                        {
                            Code = "MXN",
                            IsDefault = false,
                            Name = "Mexican peso",
                            Symbol = "$",
                            Version = 0
                        },
                        new
                        {
                            Code = "MYR",
                            IsDefault = false,
                            Name = "Malaysian ringgit",
                            Symbol = "RM",
                            Version = 0
                        },
                        new
                        {
                            Code = "MZM",
                            IsDefault = false,
                            Name = "Mozambican metical",
                            Symbol = "MTn",
                            Version = 0
                        },
                        new
                        {
                            Code = "NAD",
                            IsDefault = false,
                            Name = "Namibian dollar",
                            Symbol = "N$",
                            Version = 0
                        },
                        new
                        {
                            Code = "NGN",
                            IsDefault = false,
                            Name = "Nigerian naira",
                            Symbol = "₦",
                            Version = 0
                        },
                        new
                        {
                            Code = "NIO",
                            IsDefault = false,
                            Name = "Nicaraguan córdoba",
                            Symbol = "C$",
                            Version = 0
                        },
                        new
                        {
                            Code = "NOK",
                            IsDefault = false,
                            Name = "Norwegian krone",
                            Symbol = "kr",
                            Version = 0
                        },
                        new
                        {
                            Code = "NPR",
                            IsDefault = false,
                            Name = "Nepalese rupee",
                            Symbol = "NRs",
                            Version = 0
                        },
                        new
                        {
                            Code = "NZD",
                            IsDefault = false,
                            Name = "New Zealand dollar",
                            Symbol = "NZ$",
                            Version = 0
                        },
                        new
                        {
                            Code = "OMR",
                            IsDefault = false,
                            Name = "Omani rial",
                            Symbol = "OMR",
                            Version = 0
                        },
                        new
                        {
                            Code = "PAB",
                            IsDefault = false,
                            Name = "Panamanian balboa",
                            Symbol = "B/.",
                            Version = 0
                        },
                        new
                        {
                            Code = "PEN",
                            IsDefault = false,
                            Name = "Peruvian nuevo sol",
                            Symbol = "S/.",
                            Version = 0
                        },
                        new
                        {
                            Code = "PGK",
                            IsDefault = false,
                            Name = "Papua New Guinean kina",
                            Symbol = "K",
                            Version = 0
                        },
                        new
                        {
                            Code = "PHP",
                            IsDefault = false,
                            Name = "Philippine peso",
                            Symbol = "₱",
                            Version = 0
                        },
                        new
                        {
                            Code = "PKR",
                            IsDefault = false,
                            Name = "Pakistani rupee",
                            Symbol = "Rs.",
                            Version = 0
                        },
                        new
                        {
                            Code = "PLN",
                            IsDefault = false,
                            Name = "Polish zloty",
                            Symbol = "zł",
                            Version = 0
                        },
                        new
                        {
                            Code = "PYG",
                            IsDefault = false,
                            Name = "Paraguayan guarani",
                            Symbol = "₲",
                            Version = 0
                        },
                        new
                        {
                            Code = "QAR",
                            IsDefault = false,
                            Name = "Qatari riyal",
                            Symbol = "QR",
                            Version = 0
                        },
                        new
                        {
                            Code = "RON",
                            IsDefault = false,
                            Name = "Romanian leu",
                            Symbol = "L",
                            Version = 0
                        },
                        new
                        {
                            Code = "RSD",
                            IsDefault = false,
                            Name = "Serbian dinar",
                            Symbol = "din.",
                            Version = 0
                        },
                        new
                        {
                            Code = "RUB",
                            IsDefault = false,
                            Name = "Russian ruble",
                            Symbol = "R",
                            Version = 0
                        },
                        new
                        {
                            Code = "SAR",
                            IsDefault = false,
                            Name = "Saudi riyal",
                            Symbol = "SR",
                            Version = 0
                        },
                        new
                        {
                            Code = "SBD",
                            IsDefault = false,
                            Name = "Solomon Islands dollar",
                            Symbol = "SI$",
                            Version = 0
                        },
                        new
                        {
                            Code = "SCR",
                            IsDefault = false,
                            Name = "Seychellois rupee",
                            Symbol = "SR",
                            Version = 0
                        },
                        new
                        {
                            Code = "SDG",
                            IsDefault = false,
                            Name = "Sudanese pound",
                            Symbol = "SDG",
                            Version = 0
                        },
                        new
                        {
                            Code = "SEK",
                            IsDefault = false,
                            Name = "Swedish krona",
                            Symbol = "kr",
                            Version = 0
                        },
                        new
                        {
                            Code = "SGD",
                            IsDefault = false,
                            Name = "Singapore dollar",
                            Symbol = "S$",
                            Version = 0
                        },
                        new
                        {
                            Code = "SHP",
                            IsDefault = false,
                            Name = "Saint Helena pound",
                            Symbol = "£",
                            Version = 0
                        },
                        new
                        {
                            Code = "SLL",
                            IsDefault = false,
                            Name = "Sierra Leonean leone",
                            Symbol = "Le",
                            Version = 0
                        },
                        new
                        {
                            Code = "SOS",
                            IsDefault = false,
                            Name = "Somali shilling",
                            Symbol = "Sh.",
                            Version = 0
                        },
                        new
                        {
                            Code = "SRD",
                            IsDefault = false,
                            Name = "Surinamese dollar",
                            Symbol = "$",
                            Version = 0
                        },
                        new
                        {
                            Code = "SYP",
                            IsDefault = false,
                            Name = "Syrian pound",
                            Symbol = "LS",
                            Version = 0
                        },
                        new
                        {
                            Code = "SZL",
                            IsDefault = false,
                            Name = "Swazi lilangeni",
                            Symbol = "E",
                            Version = 0
                        },
                        new
                        {
                            Code = "THB",
                            IsDefault = false,
                            Name = "Thai baht",
                            Symbol = "฿",
                            Version = 0
                        },
                        new
                        {
                            Code = "TJS",
                            IsDefault = false,
                            Name = "Tajikistani somoni",
                            Symbol = "TJS",
                            Version = 0
                        },
                        new
                        {
                            Code = "TMT",
                            IsDefault = false,
                            Name = "Turkmen manat",
                            Symbol = "m",
                            Version = 0
                        },
                        new
                        {
                            Code = "TND",
                            IsDefault = false,
                            Name = "Tunisian dinar",
                            Symbol = "DT",
                            Version = 0
                        },
                        new
                        {
                            Code = "TRY",
                            IsDefault = false,
                            Name = "Turkish new lira",
                            Symbol = "TRY",
                            Version = 0
                        },
                        new
                        {
                            Code = "TTD",
                            IsDefault = false,
                            Name = "Trinidad and Tobago dollar",
                            Symbol = "TT$",
                            Version = 0
                        },
                        new
                        {
                            Code = "TWD",
                            IsDefault = false,
                            Name = "New Taiwan dollar",
                            Symbol = "NT$",
                            Version = 0
                        },
                        new
                        {
                            Code = "TZS",
                            IsDefault = false,
                            Name = "Tanzanian shilling",
                            Symbol = "TZS",
                            Version = 0
                        },
                        new
                        {
                            Code = "UAH",
                            IsDefault = false,
                            Name = "Ukrainian hryvnia",
                            Symbol = "UAH",
                            Version = 0
                        },
                        new
                        {
                            Code = "UGX",
                            IsDefault = false,
                            Name = "Ugandan shilling",
                            Symbol = "USh",
                            Version = 0
                        },
                        new
                        {
                            Code = "USD",
                            IsDefault = true,
                            Name = "United States dollar",
                            Symbol = "US$",
                            Version = 0
                        },
                        new
                        {
                            Code = "UYU",
                            IsDefault = false,
                            Name = "Uruguayan peso",
                            Symbol = "$U",
                            Version = 0
                        },
                        new
                        {
                            Code = "UZS",
                            IsDefault = false,
                            Name = "Uzbekistani som",
                            Symbol = "UZS",
                            Version = 0
                        },
                        new
                        {
                            Code = "VEB",
                            IsDefault = false,
                            Name = "Venezuelan bolivar",
                            Symbol = "Bs",
                            Version = 0
                        },
                        new
                        {
                            Code = "VND",
                            IsDefault = false,
                            Name = "Vietnamese dong",
                            Symbol = "₫",
                            Version = 0
                        },
                        new
                        {
                            Code = "VUV",
                            IsDefault = false,
                            Name = "Vanuatu vatu",
                            Symbol = "VT",
                            Version = 0
                        },
                        new
                        {
                            Code = "WST",
                            IsDefault = false,
                            Name = "Samoan tala",
                            Symbol = "WS$",
                            Version = 0
                        },
                        new
                        {
                            Code = "XAF",
                            IsDefault = false,
                            Name = "Central African CFA franc",
                            Symbol = "CFA",
                            Version = 0
                        },
                        new
                        {
                            Code = "XCD",
                            IsDefault = false,
                            Name = "East Caribbean dollar",
                            Symbol = "EC$",
                            Version = 0
                        },
                        new
                        {
                            Code = "XDR",
                            IsDefault = false,
                            Name = "Special Drawing Rights",
                            Symbol = "SDR",
                            Version = 0
                        },
                        new
                        {
                            Code = "XOF",
                            IsDefault = false,
                            Name = "West African CFA franc",
                            Symbol = "CFA",
                            Version = 0
                        },
                        new
                        {
                            Code = "XPF",
                            IsDefault = false,
                            Name = "CFP franc",
                            Symbol = "F",
                            Version = 0
                        },
                        new
                        {
                            Code = "YER",
                            IsDefault = false,
                            Name = "Yemeni rial",
                            Symbol = "YER",
                            Version = 0
                        },
                        new
                        {
                            Code = "ZAR",
                            IsDefault = false,
                            Name = "South African rand",
                            Symbol = "R",
                            Version = 0
                        },
                        new
                        {
                            Code = "ZMK",
                            IsDefault = false,
                            Name = "Zambian kwacha",
                            Symbol = "ZK",
                            Version = 0
                        },
                        new
                        {
                            Code = "ZWR",
                            IsDefault = false,
                            Name = "Zimbabwean dollar",
                            Symbol = "Z$",
                            Version = 0
                        });
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.CurrencyExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyFromCode")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CurrencyToCode")
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyToCode");

                    b.HasIndex("CurrencyFromCode", "Time");

                    b.ToTable("CurrencyExchangeRates");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.DashboardItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DashboardItems");

                    b.HasDiscriminator<string>("Item_Type").HasValue("DashboardItem");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.DataImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ErrorLogAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.InstrumentPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId", "Time");

                    b.ToTable("InstrumentPrices");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionId", "Time");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.ChartLineInstrument", b =>
                {
                    b.HasBaseType("PortEval.Domain.Models.Entities.ChartLine");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.HasIndex("InstrumentId");

                    b.HasDiscriminator().HasValue("Instrument");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.ChartLinePortfolio", b =>
                {
                    b.HasBaseType("PortEval.Domain.Models.Entities.ChartLine");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.HasIndex("PortfolioId");

                    b.HasDiscriminator().HasValue("Portfolio");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.ChartLinePosition", b =>
                {
                    b.HasBaseType("PortEval.Domain.Models.Entities.ChartLine");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasIndex("PositionId");

                    b.HasDiscriminator().HasValue("Position");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.DashboardChartItem", b =>
                {
                    b.HasBaseType("PortEval.Domain.Models.Entities.DashboardItem");

                    b.Property<int>("ChartId")
                        .HasColumnType("int");

                    b.HasIndex("ChartId");

                    b.HasDiscriminator().HasValue("Chart");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Chart", b =>
                {
                    b.OwnsOne("PortEval.Domain.Models.ValueObjects.ChartDateRange", "DateRange", b1 =>
                        {
                            b1.Property<int>("ChartId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime?>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("DateRangeEnd");

                            b1.Property<bool>("IsToDate")
                                .HasColumnType("bit")
                                .HasColumnName("IsToDate");

                            b1.Property<DateTime?>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("DateRangeStart");

                            b1.HasKey("ChartId");

                            b1.ToTable("Charts");

                            b1.WithOwner()
                                .HasForeignKey("ChartId");

                            b1.OwnsOne("PortEval.Domain.Models.ValueObjects.ToDateRange", "ToDateRange", b2 =>
                                {
                                    b2.Property<int>("ChartDateRangeChartId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<int>("Unit")
                                        .HasColumnType("int")
                                        .HasColumnName("ToDateRangeUnit");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int")
                                        .HasColumnName("ToDateRangeValue");

                                    b2.HasKey("ChartDateRangeChartId");

                                    b2.ToTable("Charts");

                                    b2.WithOwner()
                                        .HasForeignKey("ChartDateRangeChartId");
                                });

                            b1.Navigation("ToDateRange");
                        });

                    b.OwnsOne("PortEval.Domain.Models.ValueObjects.ChartTypeSettings", "TypeConfiguration", b1 =>
                        {
                            b1.Property<int>("ChartId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("CurrencyCode");

                            b1.Property<int?>("Frequency")
                                .HasColumnType("int")
                                .HasColumnName("Frequency");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("Type");

                            b1.HasKey("ChartId");

                            b1.HasIndex("CurrencyCode");

                            b1.ToTable("Charts");

                            b1.WithOwner()
                                .HasForeignKey("ChartId");

                            b1.HasOne("PortEval.Domain.Models.Entities.Currency", null)
                                .WithMany()
                                .HasForeignKey("CurrencyCode");
                        });

                    b.Navigation("DateRange");

                    b.Navigation("TypeConfiguration");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.ChartLine", b =>
                {
                    b.HasOne("PortEval.Domain.Models.Entities.Chart", "Chart")
                        .WithMany("Lines")
                        .HasForeignKey("ChartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chart");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Currency", b =>
                {
                    b.OwnsOne("PortEval.Domain.Models.ValueObjects.TrackingInformation", "TrackingInfo", b1 =>
                        {
                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("nvarchar(3)");

                            b1.Property<DateTime>("LastUpdate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("CurrencyCode");

                            b1.ToTable("Currencies");

                            b1.WithOwner()
                                .HasForeignKey("CurrencyCode");
                        });

                    b.Navigation("TrackingInfo");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.CurrencyExchangeRate", b =>
                {
                    b.HasOne("PortEval.Domain.Models.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyFromCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PortEval.Domain.Models.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyToCode");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.DashboardItem", b =>
                {
                    b.OwnsOne("PortEval.Domain.Models.ValueObjects.DashboardPosition", "Position", b1 =>
                        {
                            b1.Property<int>("DashboardItemId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Height")
                                .HasColumnType("int")
                                .HasColumnName("DashboardHeight");

                            b1.Property<int>("Width")
                                .HasColumnType("int")
                                .HasColumnName("DashboardWidth");

                            b1.Property<int>("X")
                                .HasColumnType("int")
                                .HasColumnName("DashboardPositionX");

                            b1.Property<int>("Y")
                                .HasColumnType("int")
                                .HasColumnName("DashboardPositionY");

                            b1.HasKey("DashboardItemId");

                            b1.ToTable("DashboardItems");

                            b1.WithOwner()
                                .HasForeignKey("DashboardItemId");
                        });

                    b.Navigation("Position");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Instrument", b =>
                {
                    b.HasOne("PortEval.Domain.Models.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode");

                    b.OwnsOne("PortEval.Domain.Models.ValueObjects.TrackingInformation", "TrackingInfo", b1 =>
                        {
                            b1.Property<int>("InstrumentId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("LastUpdate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("InstrumentId");

                            b1.ToTable("Instruments");

                            b1.WithOwner()
                                .HasForeignKey("InstrumentId");
                        });

                    b.Navigation("TrackingInfo");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.InstrumentPrice", b =>
                {
                    b.HasOne("PortEval.Domain.Models.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Portfolio", b =>
                {
                    b.HasOne("PortEval.Domain.Models.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Position", b =>
                {
                    b.HasOne("PortEval.Domain.Models.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortEval.Domain.Models.Entities.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Transaction", b =>
                {
                    b.HasOne("PortEval.Domain.Models.Entities.Position", "Position")
                        .WithMany("Transactions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.ChartLineInstrument", b =>
                {
                    b.HasOne("PortEval.Domain.Models.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.ChartLinePortfolio", b =>
                {
                    b.HasOne("PortEval.Domain.Models.Entities.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.ChartLinePosition", b =>
                {
                    b.HasOne("PortEval.Domain.Models.Entities.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.DashboardChartItem", b =>
                {
                    b.HasOne("PortEval.Domain.Models.Entities.Chart", null)
                        .WithMany()
                        .HasForeignKey("ChartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Chart", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("PortEval.Domain.Models.Entities.Position", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
